# Control analyses

```{r setup}
#| cache: false
# Packages
library(scales)
library(ggstance)
library(memoise)
library(cachem)
library(lme4)
library(broom.mixed)
library(lubridate)
library(janitor)
library(patchwork)
library(tidyverse)

# Common options
source("_common.R")

cd <- cache_disk("memoise_cache", max_size = Inf)

oo <- c(
  "Life_satisfaction", "Negative_experiences", "Positive_experiences",
  "Anxiety", "Depression", "Selfharm"
)

fits <- tibble(outcome = oo) %>%
  mutate(outcome = factor(outcome, levels = oo))

dat <- readRDS("data/data-all.rds")
```


Here, we analyse associations between other country-level indicators and well-being and mental health.

## Human development index

```{r}
itu <- read_rds("data/itu.rds")
itu %>%
  mutate(year = make_date(year)) %>%
  ggplot(aes(year, hdi)) +
  scale_y_continuous(
    "Value",
    labels = ~percent(., .1),
    breaks = pretty_breaks(),
    expand = expansion(.05)
  ) +
  scale_x_date(
    "Year",
    breaks = make_date(c(2005, 2010, 2015, 2020)),
    date_labels = "'%y",
    expand = expansion(.02)
  ) +
  geom_line(
    aes(group = interaction(country)),
    alpha = .25, size = .4, color = "dodgerblue1"
  ) +
  facet_grid(
    ~ region,
    scales = "free_y",
    labeller = as_labeller(function(x) str_replace(x, "_", "\n"))
  ) +
  theme(
    aspect.ratio = 1,
    legend.position = "none",
    panel.spacing.x = unit(4, "pt"),
    panel.spacing.y = unit(6, "pt"),
    axis.title.y = element_blank()
  )
```

```{r}
# Merge to country-aggregated outcomes
tmp <- dat %>% 
  mutate(year = (year * 10 + 2010)) %>% 
  # Aggregate to country-year means (across age & sex)
  group_by(region, country, year, outcome) %>% 
  summarise(
    val = mean(val, na.rm = TRUE), 
  ) %>% 
  ungroup() %>% 
  # Join to country-year predictors
  left_join(itu) %>% 
  mutate(year = (year - 2010) / 10) %>% 
  drop_na(val)
```

### Between-country associations

```{r}
# Correlate country-level intercepts of outcomes and predictors
coef2 <- possibly(coef, NA)
tmp %>% 
  mutate(hdi = hdi - mean(hdi, na.rm = TRUE)) %>% 
  group_by(outcome, region, country) %>% 
  group_modify(
    ~tibble(
      mean = coef(lm(val ~ 1, data = .))[1],
      adjusted = coef2(lm(val ~ 1 + hdi, data = .))[1]
      )
  )

# Data for average levels scatterplots
dat_avg <- tmp %>%
  group_by(outcome, region, country) %>%
  summarise(
    internet = mean(internet, na.rm = TRUE),
    mobile = mean(mobile, na.rm = TRUE),
    hdi = mean(hdi, na.rm = TRUE),
    val = mean(val, na.rm = TRUE)
  ) %>%
  ungroup()

dat_avg

p_means_ols_internet <- dat_avg %>%
  ggplot(aes(y = val, col = region)) +
  scale_color_discreterainbow(
    name = "Region",
    labels = ~str_replace(., "_", " ")
  ) +
  scale_y_continuous(
    "Mean outcome",
    labels = ~percent(./100, .1),
    breaks = extended_breaks()
  ) +
  geom_point(
    shape = 1, size = 1.0, alpha = .75
  ) +
  facet_wrap(
    ~outcome,
    scales = "free", nrow = 1,
    labeller = as_labeller(~str_replace(., "_", " ") %>% str_to_title(.))
  ) +
  guides(
    color = guide_legend(
      override.aes = list(alpha = 1, shape = 16, size = 1.5)
    )
  ) +
  theme(
    aspect.ratio = 1
  )

p_means_ols_internet <- p_means_ols_internet +
  aes(x = internet) +
  scale_x_continuous(
    "Mean internet users per capita",
    breaks = seq(0, 1, by = .25),
    labels = ~percent(.),
    limits = 0:1
  )
p_means_ols_mobile <- p_means_ols_internet +
  aes(x = mobile) +
  scale_x_continuous(
    "Mean mobile internet subscriptions per capita",
    breaks = seq(0, 1.5, by = .5),
    labels = ~percent(.),
    limits = c(0, 1.5)
  )

(p_means_ols_internet | 
    p_delta_ols_internet | 
    p_means_ols_mobile | 
    p_delta_ols_mobile
) +
  plot_layout(nrow = 4, guides = "collect")

agg_png(
  "figures/Fig-country-correlations-OLS.png",
  width = W, height = W*0.8, units = "in", res = 400
)
last_plot()
dev.off()

# Coefficient plot
means_ols_cors <- dat_avg %>%
  group_by(outcome) %>%
  group_modify(
    ~tidy(lm(scale(val) ~ scale(internet), data = .), conf.int = TRUE)
  ) %>%
  filter(term != "(Intercept)")
delta_ols_cors <- delta_ols %>%
  group_by(outcome) %>%
  group_modify(
    ~tidy(lm(scale(estimate_val) ~ scale(estimate_internet), data = .), conf.int = TRUE)
  ) %>%
  filter(term != "(Intercept)")
cor_pars_ols <- bind_rows(
  "Means" = means_ols_cors,
  "Deltas" = delta_ols_cors,
  .id = "type"
)
cor_pars_ols %>%
  mutate(type = fct_rev(type)) %>%
  mutate(outcome = fct_rev(factor(outcome, levels = oo))) %>%
  ggplot(aes(estimate, outcome)) +
  geom_vline(xintercept = 0, lty = 2, size = .25) +
  geom_pointrangeh(aes(xmin = conf.low, xmax = conf.high)) +
  facet_wrap("type") +
  labs(x = "Correlation") +
  theme(axis.title.y = element_blank())
```


### Within-country associations

```{r}
predictors <- c("internet", "i_cw", "i1", "i1_cw", "hdi", "h_cw", "h1", "h1_cw")
lmer2 <- memoise(lmer, cache = cd)
out <- fits %>% 
  crossing(
    x = predictors
  ) %>% 
  mutate(
    frm = str_glue(
      "val ~ {x} + year + ({x} + year | country) + ({x} + year | region)"
    )
  ) %>% 
  mutate(
    fit = map2(
      frm, outcome, 
      ~lmer2(.x, data = tmp %>% filter(outcome == .y))
    )
  )

pars <- out %>% 
  mutate(
    fixef = map(
      fit,
      ~tidy(.x, effects = "fixed", conf.int = TRUE)
    ),
    coef_region = map(
      fit,
      ~coef(.x)$region %>% 
        rownames_to_column("region") %>% 
        pivot_longer(-region, names_to = "term", values_to = "estimate")
    )
  ) %>% 
  mutate(
    x = factor(
      x,
      levels = predictors
    )
  ) %>% 
  select(-fit)
  
pars %>%
  select(-coef_region) %>% 
  unnest(fixef) %>% 
  filter(!(term %in% c("(Intercept)", "year"))) %>% 
  ggplot(aes(estimate, x)) +
  scale_y_discrete("Predictor", limits = rev) +
  scale_x_continuous(
    "Conditional effect of 10% change in predictor",
    breaks = extended_breaks(),
    # Visualize conditional effect of 10% change on x
    # Modelled (0-100), change to proportion so percentage is correct
    labels = ~percent(./1000)
  ) +
  geom_vline(xintercept = 0, lty = 2, size = .25) +
  geom_point(
    data = pars %>% 
      select(-fixef) %>% 
      unnest(coef_region) %>% 
      filter(!(term %in% c("(Intercept)", "year"))),
    size = .75, shape = 1,
    position = position_nudge(y = -.2)
  ) +
  geom_pointrangeh(
    aes(xmin = conf.low, xmax = conf.high),
    position = position_dodge2v(.25),
    fatten = 3
  ) +
  facet_wrap("outcome", scales = "free_x", nrow = 2)
```

```{r}
library(mgcv)
tmp2 <- tmp %>% 
  filter(outcome == "Life_satisfaction") %>% 
  mutate(country = factor(country))

fit <- gamm(
  val ~ s(year, by = region) + s(internet, by = region), 
  random = list(
    # region = ~1,
    country = ~1
  ),
  data = tmp2,
  method = "REML"
  )
summary(fit$gam)
summary(fit$lme)
library(gratia)
library(ggh4x)
draw(fit, nrow = 2)
# Draw only for values in data for each region

smooth_year <- smooth_estimates(
    fit, 
    smooth = "s(year)", 
    partial_match = TRUE
  ) %>%
  rename(X = year)
smooth_internet <- smooth_estimates(
    fit, 
    smooth = "s(internet)", 
    partial_match = TRUE
) %>% 
  left_join(
    tmp2 %>% 
      group_by(region) %>% 
      summarise(min = min(internet, na.rm = TRUE))
  ) %>% 
  filter(internet >= min | is.na(internet)) %>% 
  rename(X = internet)
bind_rows(
  "Time" = smooth_year,
  "Internet" = smooth_internet,
  .id = "Predictor"
) %>% 
  ggplot(aes(X, est)) +
  scale_x_continuous(
    breaks = extended_breaks(),
    labels = ~percent(.)
  ) +
  scale_y_continuous(
    breaks = extended_breaks(),
    labels = ~percent(./100)
  ) +
  geom_ribbon(aes(ymin = est-se, ymax = est+se), alpha = .2) +
  geom_line() +
  facet_grid2(Predictor~region, scales = "free", independent = "x")

library(emmeans)
emtrends(fit, var = "internet", data = fit$lme$data, )
emmeans(
  fit, 
  "internet", 
  at = group_by(tmp2, region) %>% 
    summarise(internet = min(internet, na.rm = TRUE)), 
  data = fit$lme$data,
  by = "region"
)
```

