# Describe

```{r packages}
#| results: 'hide'
# Packages
library(ggtext)
library(scales)
library(patchwork)
library(lubridate)
library(kableExtra)
library(ggstance)
library(tidyverse)
```

```{r}
itu <- read_rds("data/itu.rds")
gwp <- read_rds("data/gwp.rds")
gbd <- read_rds("data/gbd.rds")
```

## Combined figure

A figure that shows all variables (outcome means and internet rates) over time together.

```{r}
# Stack data sets
# Assume all outcomes are proportions (0-1)
dat_all <- bind_rows(
  gwp,
  gbd,
  itu %>% mutate(cause = "Internet", val = internet)
) %>% 
  mutate(cause = fct_inorder(str_replace(cause, " ", "\n"))) %>% 
  group_by(region, country, year, cause) %>% 
  summarise(mean = mean(val, na.rm = TRUE)) %>% 
  ungroup()

# Draw small multiples figure, outcomes x regions
dat_all %>% 
  mutate(year = make_date(year)) %>% 
  ggplot(aes(year, mean)) +
  scale_y_continuous(
    "Value",
    labels = function(x) percent(x, .01) %>% str_remove("\\.00"),
    breaks = pretty_breaks()
  ) +
  scale_x_date(
    "Year",
    breaks = make_date(c(2000, 2005, 2010, 2015, 2020)), 
    date_labels = "'%y", 
    expand = expansion(.02)
  ) +
  geom_line(
    aes(group = interaction(country, cause)), 
    alpha = .25, size = .4, color = "dodgerblue1"
  ) +
  stat_summary(
    fun = mean, geom = "line", 
    size = .6, color = "dodgerblue4"
  ) +
  # Ensure 0-100 limits for gwp outcomes
  # geom_blank(
  #   data = crossing(
  #     region = "Africa", 
  #     country = NA, 
  #     mean = c(0, 1), 
  #     cause = unique(gwp$cause),
  #     year = make_date(2001)
  #     )
  # ) +
  facet_grid(cause~region, scales = "free_y") +
  theme(
    legend.position = "none",
    panel.spacing = unit(3, "pt")
  )
```

## Internet use trends

```{r}
itu %>% 
  filter(year %in% c(2001, 2019)) %>% 
  select(region, country, year, internet) %>% 
  pivot_wider(names_from = year, values_from = internet) %>% 
  select(-country) %>% 
  tbl_summary(by = region) %>% 
  add_overall()
itu %>% 
  group_by(country) %>% 
  summarise(x = sum(!is.na(internet))) %>% 
  arrange(x)
itu %>% 
  drop_na(internet) %>% 
  distinct(country) %>% 
  nrow
```

```{r}
itu %>% 
  mutate(year = make_date(year)) %>%
  mutate(mobile = if_else(mobile > 1.50, NaN, mobile)) %>% 
  pivot_longer(fixed:mobile) %>% 
  mutate(name = str_to_title(name)) %>% 
  mutate(name = fct_inorder(name)) %>% 
  ggplot(aes(x = year, y = value)) +
  # coord_cartesian(ylim = c(0, 1.00)) +
  scale_y_continuous(
    "Subscriptions by population",
    # breaks = c(0, .25, .5, .75, 1),
    labels = percent,
    expand = expansion(c(0.025, 0.1))
  ) +
  scale_x_date(
    "Year",
    breaks = make_date(c(2000, 2005, 2010, 2015)), 
    date_labels = "'%y", 
    expand = expansion(.02)
  ) +
  # Ensure all axes go up to 100%
  geom_blank(
    data = tibble(
      region = "Africa", 
      country = NA, 
      value = 1, 
      year = make_date(2001))
  ) +
  geom_line(
    aes(group = country),
    alpha = .25, size = .4, color = "dodgerblue1"
  ) +
  stat_summary(
    fun = mean, geom = "line", 
    size = .6, color = "dodgerblue4"
  ) +
  facet_grid(name~region, scales = "free_y") +
  theme(
    legend.position = "none",
    panel.spacing = unit(2, "pt")
  )
```

## Mental health

```{r eval = FALSE}
pa <- gbd %>% 
  ggplot(aes(year, val, group = country, col = region)) +
  scale_y_continuous(
    "Rate in 100 people",
    breaks = pretty_breaks()
  ) +
  scale_x_continuous(
    breaks = c(2000, 2005, 2010, 2015, 2020),
    labels = c("'00", "'05", "'10", "'15", "'20")
  ) +
  stat_summary(fun = mean, geom = "line", size = .5) +
  facet_grid(cause~region, scales = "free_y") +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
  )
pb <- gbd %>% 
  mutate(Group = str_glue("{sex} ({age})")) %>% 
  ggplot(aes(year, val, col = Group)) +
  scale_color_brewer(palette = "Paired") +
  scale_y_continuous(
    "Rate in 100 people",
    breaks = pretty_breaks()
  ) +
  scale_x_continuous(
    "Year",
    breaks = c(2000, 2005, 2010, 2015, 2020),
    labels = c("'00", "'05", "'10", "'15", "'20")
  ) +
  stat_summary(fun = mean, geom = "line", size = .6) +
  facet_grid(cause~region, scales = "free_y")

(pa / pb) +
  plot_annotation(tag_levels = "A")
```

## Countries

### Internet

```{r}
small_multiples_internet <- function(data, region) {
  data %>% 
    filter(region == {{region}}) %>% 
    mutate(year = make_date(year)) %>% 
    ggplot(
      aes(
        year, internet
      )
    ) +
    scale_x_date(
      "Year",
      breaks = make_date(c(2005, 2010, 2015, 2020)), 
      date_labels = "'%y", 
      expand = expansion(.02)
    ) +
    scale_y_continuous(
      "Internet users",
      limits = c(0, 1),
      labels = percent
    ) +
    labs(caption = str_replace({{region}}, "\n", " ")) +
    geom_line() +
    facet_wrap(~country) +
    theme(
      legend.position = "none",
      panel.grid.major = element_line(
        size = .1, linetype = 2, color = "gray30"
      )
    )
}
regions <- sort(unique(itu$region))
map(regions, ~small_multiples_internet(itu, .x))
```

### Mental health

```{r}
small_multiples_outcome <- function(data, cause, region) {
  data %>% 
    filter(cause == {{cause}}) %>% 
    filter(region == {{region}}) %>% 
    mutate(year = make_date(year)) %>% 
    ggplot(
      aes(
        year, val, 
        col = age, 
        fill = age,
        lty = sex,
        group = interaction(sex, age)
      )
    ) +
    scale_color_brewer(palette = "Dark2", aesthetics = c("fill", "color")) +
    scale_x_date(
      "Year",
      breaks = make_date(c(2000, 2005, 2010, 2015)), 
      date_labels = "'%y", 
      expand = expansion(.02)
    ) +
    scale_y_continuous(
      {{cause}},
      labels = percent
    ) +
    geom_ribbon(
      aes(ymin = val-se*1.96, ymax = val+se*1.96),
      alpha = .125, col = NA
    ) +
    labs(caption = str_replace({{region}}, "\n", " ")) +
    geom_line() +
    facet_wrap(~country) +
    theme(
      legend.position = "none",
      panel.grid.major = element_line(
        size = .1, linetype = 2, color = "gray30"
      )
    )
}
```

#### Life satisfaction

```{r}
# Do this first just to show the legend
small_multiples_outcome(gwp, "Life\nsatisfaction", "Anglo") +
  theme(legend.position = "bottom")

map(
  regions[regions!="Anglo"], 
  ~small_multiples_outcome(gwp, "Life\nsatisfaction", .x)
)
```

#### Negative experiences

```{r}
# Do this first just to show the legend
small_multiples_outcome(gwp, "Negative\nexperiences", "Anglo") +
  theme(legend.position = "bottom")

map(
  regions[regions!="Anglo"], 
  ~small_multiples_outcome(gwp, "Negative\nexperiences", .x)
)
```

#### Positive experiences

```{r}
# Do this first just to show the legend
small_multiples_outcome(gwp, "Positive\nexperiences", "Anglo") +
  theme(legend.position = "bottom")

map(
  regions[regions!="Anglo"], 
  ~small_multiples_outcome(gwp, "Positive\nexperiences", .x)
)
```

#### Anxiety

```{r}
small_multiples_outcome(gbd, "Anxiety", "Anglo") +
  theme(legend.position = "bottom")

map(
  regions[regions!="Anglo"], 
  ~small_multiples_outcome(gbd, "Anxiety", .x)
)
```

#### Depression

```{r}
map(
  regions[regions!="Anglo"], 
  ~small_multiples_outcome(gbd, "Depression", .x)
)
```

#### Self harm

```{r}
map(
  regions[regions!="Anglo"], 
  ~small_multiples_outcome(gbd, "Selfharm", .x)
)
```

