# Other internet metrics

In this section we reproduce Model 2 results from @sec-associations but instead of using the ITU internet user proportions, we look at fixed and mobile broadband subscription percentages as predictors.

```{r setup}
#| cache: false
# Packages
library(scales)
library(ggtext)
library(lubridate)
library(kableExtra)
library(ggstance)
library(mgcv)
library(brms)
library(cmdstanr)
library(ellipse)
library(ggh4x)
library(tidybayes)
library(ggdist)
library(posterior)
library(parameters)
library(emmeans)
library(broom)
library(tidyverse)
```


```{r}
# Load data sets
itu <- read_rds("data/itu.rds")
gwp <- read_rds("data/gwp.rds")
gbd <- read_rds("data/gbd.rds")

# Load models
oo <- c(
  "Life_satisfaction", "Negative_experiences", "Positive_experiences",
  "Anxiety", "Depression", "Selfharm"
)
fits <- tibble(outcome = oo) %>% 
  mutate(outcome = factor(outcome, levels = oo)) %>% 
  mutate(
    fitf = map(
      outcome, 
      ~read_rds(str_glue("models/brm-{.x}-2-fixed.rds"))
    ),
    fitm = map(
      outcome, 
      ~read_rds(str_glue("models/brm-{.x}-2-mobile.rds"))
    )
  )
```

## Data figures

```{r}
itu %>% 
  select(-internet) %>% 
  rename(Fixed = fixed, Mobile = mobile) %>% 
  pivot_longer(c(Fixed, Mobile)) %>% 
  # filter(value < 2) %>% 
  mutate(year = make_date(year)) %>%
  ggplot(aes(year, value)) +
  scale_y_continuous(
    "Value",
    labels = function(x) percent(x, .01) %>% str_remove("\\.00"),
    breaks = pretty_breaks()
  ) +
  scale_x_date(
    "Year",
    date_breaks = "5 years",
    date_labels = "'%y",
    expand = expansion(.02)
  ) +
  geom_line(
    aes(group = country),
    alpha = .25, size = .4, color = "dodgerblue1"
  ) +
  stat_summary(
    fun = mean, geom = "line",
    size = .6, color = "dodgerblue4"
  ) +
  facet_grid(
    name ~ region,
    scales = "free_y",
    labeller = as_labeller(function(x) str_replace(x, "_", "\n"))
  ) +
  theme(
    aspect.ratio = 2,
    legend.position = "none",
    panel.spacing = unit(3, "pt"),
    axis.title.y = element_blank()
  )
```

## Fixed broadband

### Forest plot

```{r}
#| column: screen-inset-right
#| fig-width: 13
#| fig-height: 8
#| fig-cap: "Forest plot of internet associations"
#| label: fig-forest-fixed

# Calculate parameters at all levels of analysis
p_draws <- fits %>%
  mutate(pdraws = map(fitf, ~pdraws(.x, "f1_cw"))) %>%
  select(outcome, pdraws) %>%
  unnest(pdraws)
p_sums <- fits %>%
  mutate(psums = map(fitf, ~psums(.x, "f1_cw"))) %>%
  select(outcome, psums) %>%
  unnest(psums)
p_draws <- p_draws %>%
  mutate(region = fct_relevel(region, "Average")) %>%
  mutate(outcome = str_replace(outcome, "_", " ")) %>%
  mutate(outcome = factor(outcome, levels = str_replace(oo, "_", " ")))
p_sums <- p_sums %>%
  mutate(region = fct_relevel(region, "Average")) %>%
  mutate(outcome = str_replace(outcome, "_", " ")) %>%
  mutate(outcome = factor(outcome, levels = str_replace(oo, "_", " ")))

p_draws %>%
  mutate(is_average = region == "Average") %>%
  ggplot(aes(value, region, fill = is_average)) +
  scale_fill_manual(values = c("dodgerblue1", "dodgerblue4")) +
  scale_alpha_manual(values = c(.4, .8)) +
  geom_vline(xintercept = 0, lty = 2, size = .2) +
  scale_shape_manual(values = c(21, 19)) +
  scale_y_discrete(
    expand = expansion(c(0.01, .1)),
    labels = function(x) {
      if_else(x == "Average", "**Average**", x) %>%
        str_replace("_", " ")
    }
  ) +
  scale_x_continuous(
    "Conditional effect of 100% increase in fixed broadband subscriptions",
    breaks = pretty_breaks(),
    labels = function(x) percent(x / 100, .01) %>% str_remove("\\.00"),
    expand = expansion(c(.1, .1))
  ) +
  stat_halfeye(
    point_interval = NULL, normalize = "panels",
    height = .75, adjust = 1,
    aes(alpha = is_average)
  ) +
  # Add country points
  geom_point(
    data = p_sums %>%
      drop_na(country) %>%
      mutate(is_average = TRUE),
    aes(x = Estimate), size = 1, col = "dodgerblue1",
    position = position_nudge(0, -0.075), alpha = .4
  ) +
  stat_pointinterval(
    alpha = 1, .width = c(.95),
    interval_size = 1,
    point_size = 1.75,
    fill = "white",
    aes(shape = after_stat(xmin > 0 | xmax < 0)),
    position = position_nudge(0, 0)
  ) +
  geom_richtext(
    data = p_sums %>%
      filter(is.na(country)) %>%
      mutate(is_average = region == "Average") %>%
      mutate(
        across(
          where(is.numeric),
          ~ if_else(
            outcome == "Selfharm",
            percent(. / 100, .001),
            percent(. / 100, .01)
          )
        )
      ),
    family = Font,
    alpha = 1, size = 3, hjust = 1, vjust = 0.2,
    fill = NA, label.color = NA,
    aes(
      x = Inf,
      label = str_glue("{Estimate}<br>[{Q2.5}, {Q97.5}]")
    )
  ) +
  facet_wrap(
    "outcome",
    nrow = 2, scales = "free_x"
  ) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_markdown(),
    legend.position = "none"
  )
```

### Between-country associations

```{r}
#| column: page-right
#| fig.width: 8
#| fig.height: 6
#| fig-cap: "Between-country associations"
#| label: fig-cb1-fixed

fitted_cb1 <- function(x) {
  newx <- x$data %>%
    group_by(outcome, region, country) %>%
    summarise(f1_cb = unique(f1_cb), val = mean(val, na.rm = TRUE)) %>% 
    mutate(f1_cw = 0, year = 0, sex = NA, age = NA, se = 0) %>% 
    ungroup()

  newy <- bind_cols(
    newx,
    as.data.frame(
      fitted(
        x, 
        newdata = newx, 
        re_formula = NA
        )
    )
  ) %>%
    select(-outcome)
  newy
}
tmp <- fits %>% 
  mutate(out = map(fitf, fitted_cb1)) %>% 
  select(outcome, out) %>%
  unnest(out)

cb1_pars <- fits %>%
  mutate(
    out = map(
      fitf,
      ~ as_draws_df(
        .x,
        variable = "b_f1_cb"
      ) %>%
        summarise_draws(mean, sd, ~ quantile2(., probs = c(.025, .975)))
    )
  ) %>%
  select(outcome, out) %>%
  unnest(out) %>%
  mutate(across(where(is.numeric), ~ number(., .01)))

tmp %>% 
  ggplot(aes(f1_cb, val)) +
  scale_x_continuous(
    "Between-country centered fixed broadband subscriptions",
    labels = ~percent(.)
  ) +
  scale_y_continuous(
    "Value",
    labels = ~percent(./100)
  ) +
  geom_point(
    shape = 1, size = 1, alpha = .75, col = "dodgerblue1"
  ) +
  geom_ribbon(
    aes(ymin = Q2.5, ymax = Q97.5),
    alpha = .2, fill = "dodgerblue1"
    ) +
  geom_line(aes(y = Estimate), col = "dodgerblue4") +
  geom_text(
    data = cb1_pars,
    aes(x = -Inf, y = Inf, label = str_glue("{mean} [{q2.5}, {q97.5}]")),
    vjust = 1.3, hjust = -0.025, family = Font
  ) +
  facet_wrap(
    "outcome",
    scales = "free_y", nrow = 2,
    labeller = as_labeller(~str_replace(., "_", " "))
  ) +
  theme(
    aspect.ratio = 1,
    axis.title.y = element_blank()
  )
```

## Mobile broadband

### Forest plot

```{r}
#| column: screen-inset-right
#| fig-width: 13
#| fig-height: 8
#| fig-cap: "Forest plot of internet associations"
#| label: fig-forest-mobile

# Calculate parameters at all levels of analysis
p_draws <- fits %>%
  mutate(pdraws = map(fitm, ~pdraws(.x, "m1_cw"))) %>%
  select(outcome, pdraws) %>%
  unnest(pdraws)
p_sums <- fits %>%
  mutate(psums = map(fitm, ~psums(.x, "m1_cw"))) %>%
  select(outcome, psums) %>%
  unnest(psums)
p_draws <- p_draws %>%
  mutate(region = fct_relevel(region, "Average")) %>%
  mutate(outcome = str_replace(outcome, "_", " ")) %>%
  mutate(outcome = factor(outcome, levels = str_replace(oo, "_", " ")))
p_sums <- p_sums %>%
  mutate(region = fct_relevel(region, "Average")) %>%
  mutate(outcome = str_replace(outcome, "_", " ")) %>%
  mutate(outcome = factor(outcome, levels = str_replace(oo, "_", " ")))

p_draws %>%
  mutate(is_average = region == "Average") %>%
  ggplot(aes(value, region, fill = is_average)) +
  scale_fill_manual(values = c("dodgerblue1", "dodgerblue4")) +
  scale_alpha_manual(values = c(.4, .8)) +
  geom_vline(xintercept = 0, lty = 2, size = .2) +
  scale_shape_manual(values = c(21, 19)) +
  scale_y_discrete(
    expand = expansion(c(0.01, .1)),
    labels = function(x) {
      if_else(x == "Average", "**Average**", x) %>%
        str_replace("_", " ")
    }
  ) +
  scale_x_continuous(
    "Conditional effect of 100% increase in mobile broadband subscriptions",
    breaks = pretty_breaks(),
    labels = function(x) percent(x / 100, .01) %>% str_remove("\\.00"),
    expand = expansion(c(.1, .1))
  ) +
  stat_halfeye(
    point_interval = NULL, normalize = "panels",
    height = .75, adjust = 1,
    aes(alpha = is_average)
  ) +
  # Add country points
  geom_point(
    data = p_sums %>%
      drop_na(country) %>%
      mutate(is_average = TRUE),
    aes(x = Estimate), size = 1, col = "dodgerblue1",
    position = position_nudge(0, -0.075), alpha = .4
  ) +
  stat_pointinterval(
    alpha = 1, .width = c(.95),
    interval_size = 1,
    point_size = 1.75,
    fill = "white",
    aes(shape = after_stat(xmin > 0 | xmax < 0)),
    position = position_nudge(0, 0)
  ) +
  geom_richtext(
    data = p_sums %>%
      filter(is.na(country)) %>%
      mutate(is_average = region == "Average") %>%
      mutate(
        across(
          where(is.numeric),
          ~ if_else(
            outcome == "Selfharm",
            percent(. / 100, .001),
            percent(. / 100, .01)
          )
        )
      ),
    family = Font,
    alpha = 1, size = 3, hjust = 1, vjust = 0.2,
    fill = NA, label.color = NA,
    aes(
      x = Inf,
      label = str_glue("{Estimate}<br>[{Q2.5}, {Q97.5}]")
    )
  ) +
  facet_wrap(
    "outcome",
    nrow = 2, scales = "free_x"
  ) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_markdown(),
    legend.position = "none"
  )
```

### Between-country associations

```{r}
#| column: page-right
#| fig.width: 8
#| fig.height: 6
#| fig-cap: "Between-country associations"
#| label: fig-cb1-mobile

fitted_cb1 <- function(x) {
  newx <- x$data %>%
    group_by(outcome, region, country) %>%
    summarise(m1_cb = unique(m1_cb), val = mean(val, na.rm = TRUE)) %>% 
    mutate(m1_cw = 0, year = 0, sex = NA, age = NA, se = 0) %>% 
    ungroup()

  newy <- bind_cols(
    newx,
    as.data.frame(
      fitted(
        x, 
        newdata = newx, 
        re_formula = NA
        )
    )
  ) %>%
    select(-outcome)
  newy
}
tmp <- fits %>% 
  mutate(out = map(fitm, fitted_cb1)) %>% 
  select(outcome, out) %>%
  unnest(out)

cb1_pars <- fits %>%
  mutate(
    out = map(
      fitm,
      ~ as_draws_df(
        .x,
        variable = "b_m1_cb"
      ) %>%
        summarise_draws(mean, sd, ~ quantile2(., probs = c(.025, .975)))
    )
  ) %>%
  select(outcome, out) %>%
  unnest(out) %>%
  mutate(across(where(is.numeric), ~ number(., .01)))

tmp %>% 
  ggplot(aes(m1_cb, val)) +
  scale_x_continuous(
    "Between-country centered mobile broadband subscriptions",
    labels = ~percent(.)
  ) +
  scale_y_continuous(
    "Value",
    labels = ~percent(./100)
  ) +
  geom_point(
    shape = 1, size = 1, alpha = .75, col = "dodgerblue1"
  ) +
  geom_ribbon(
    aes(ymin = Q2.5, ymax = Q97.5),
    alpha = .2, fill = "dodgerblue1"
    ) +
  geom_line(aes(y = Estimate), col = "dodgerblue4") +
  geom_text(
    data = cb1_pars,
    aes(x = -Inf, y = Inf, label = str_glue("{mean} [{q2.5}, {q97.5}]")),
    vjust = 1.3, hjust = -0.025, family = Font
  ) +
  facet_wrap(
    "outcome",
    scales = "free_y", nrow = 2,
    labeller = as_labeller(~str_replace(., "_", " "))
  ) +
  theme(
    aspect.ratio = 1,
    axis.title.y = element_blank()
  )
```
