This script implements the 3-way interactive time model with lme4.

Takes several hours.

#### lme4

```{r fit-gbd-time-lme4}
# run in parallel in background jobs using job()
# recommended to conduct this in interactive mode (rstudio)
file_path <- "output/lme4-gbd-time.rds"
if (!file.exists(file_path)) {
  library(job)
  job({fit_anx <- lmer(
    Anxiety ~ 1 + time * sex * age + 
      (1 + time * sex * age | region) +
      (1 + time * sex * age | country),
    data = gbd_wide
  )}, title = "Anxiety time (lmer)")
  job({fit_dep <- lmer(
    Depression ~ 1 + time * sex * age + 
      (1 + time * sex * age | region) +
      (1 + time * sex * age | country),
    data = gbd_wide
  )}, title = "Depression time (lmer)")
  job({fit_sel <- lmer(
    Selfharm ~ 1 + time * sex * age + 
      (1 + time * sex * age | region) +
      (1 + time * sex * age | country),
    data = gbd_wide
  )}, title = "Self harm time (lmer)")
  fits_lmer <- distinct(gbd, cause) %>% 
    mutate(fit = list(fit_anx, fit_dep, fit_sel))
  write_rds(fits_lmer, file_path)
} else {fits_lmer <- read_rds(file_path)}
```

Plot fixed effects and by demographic

```{r}
# Fixed effects parameters
fixed_effects <- fits_lmer %>% 
  mutate(out = map(fit, ~tidy(., conf.int = TRUE))) %>% 
  select(-fit) %>% 
  unnest(out) %>% 
  standardize_names() %>% 
  as_tibble() %>% 
  filter(
    Effects == "fixed", 
    Parameter != "(Intercept)"
  ) 
# Fixed effects per demographic
fixed_effects_demographics <- fits_lmer %>% 
  mutate(
    out = map(
      fit,
      ~emtrends(.x, var = "time", by = c("sex", "age")) %>% 
        parameters() %>% 
        as.data.frame()
    )
  ) %>% 
  select(-fit) %>% 
  unnest(out) %>% 
  standardize_names() %>% 
  as_tibble() %>% 
  mutate(Parameter = str_glue("{sex}\n({age})"))

# Random effects parameters
random_effects <- fits_lmer %>% 
  mutate(
    coef_region = map(
      fit, 
      ~bind_rows(
        coef(.x)$region %>% 
          as.data.frame() %>% 
          rownames_to_column("region"),
        coef(.x)$country %>% 
          as.data.frame() %>% 
          rownames_to_column("country"),
        .id = "cluster"
      ) %>% 
        mutate(cluster = factor(cluster, labels = c("region", "country")))
    )
  ) %>% 
  select(-fit) %>% 
  unnest(coef_region) %>% 
  mutate(Type = "Effects") %>%
  select(-`(Int      ,nc ercept)`)

bind_rows(
  fixed_effects,
  fixed_effects_demographics, 
  .id = "Type"
) %>% 
  mutate(Type = factor(Type, labels = c("Effects", "Time by demographic"))) %>% 
  mutate(Parameter = fct_inorder(Parameter)) %>%
  mutate(cause = factor(cause)) %>% 
  rowwise() %>% 
  mutate(
    sig = factor(
      !between(0, CI_low, CI_high), 
      levels = c(TRUE, FALSE)
    )
  ) %>% 
  ggplot(aes(Coefficient, Parameter, col = cause, shape = sig)) +
  scale_color_discrete(
    "Outcome"
  ) +
  scale_x_continuous(
    "Estimate (95%CI)"
  ) +
  scale_shape_manual(values = c(19, 21)) +
  geom_vline(xintercept = 0, size = .2, alpha = .2) +
  geom_pointrangeh(
    aes(xmin = CI_low, xmax = CI_high),
    position = position_dodge2v(.5),
    fill = "white", size = .3, fatten = 5
  ) +
  guides(shape = "none") +
  facet_wrap("Type", ncol = 2, scales = "free") +
  theme(axis.title.y = element_blank())
```
