project:
  type: book
  output-dir: docs

book:
  title: "Online analysis supplement (Vuorre & Przybylski, in prep)"
  author: "Matti Vuorre"
  date: "2022-01-28"
  page-navigation: true
  repo-url: https://github.com/digital-wellbeing/global-wbmh/
  repo-actions: [edit, issue, source]
  # downloads: [pdf]
  sharing: [twitter, facebook]
  sidebar:
    search: true
    style: "docked"
    background: "light"
    alignment: "center"
  chapters:
    - index.qmd
    - part: "Preliminaries"
      chapters:
      - clean.qmd
      - models.qmd
    - part: "Main results"
      chapters:
      - timecourses.qmd
      - associations.qmd
      - demographics.qmd
    - part: "Supplementary results"
      chapters:
      - supp-a.qmd

format:
  html:
    theme: pulse
    css: styles.css
    code-fold: true

execute:
  warning: false
  message: false
  cache: true
