project:
  type: book
  output-dir: docs

book:
  title: "Online analysis supplement (Vuorre & Przybylski, in prep)"
  author: "Matti Vuorre"
  date: "2022-03-28"
  page-navigation: true
  repo-url: https://github.com/digital-wellbeing/global-wbmh/
  repo-actions: [issue, source]
  sharing: [twitter, facebook]
  sidebar:
    search: true
    style: "docked"
    background: "light"
    alignment: "center"
  chapters:
    - index.Rmd
    - part: "Data"
      chapters:
        - 00-clean.Rmd
        - 00-describe.Rmd
    - part: "Models"
      chapters:
        - 01-models.Rmd
    - part: "Main results"
      chapters:
        - 02-results.Rmd
        - 02-correlations.Rmd

format:
  html:
    theme: pulse
    css: styles.css
    code-fold: true

execute:
  warning: false
  message: false
  cache: true
